<?php

/**
 * PluginioBlogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginioBlogTable extends ioPageTable
{
  /**
   * @param  sfGuardUser $username
   * @return Doctrine_Query
   */
  public function addAuthorQuery(sfGuardUser $user, Doctrine_Query $q = null)
  {
    if ($q === null)
    {
      $q = $this->createQuery('p');
    }

    return $q->andWhere('p.author_id = ?', $user->id);
  }
}