<?php

/**
 * PluginioBlogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginioBlogTable extends ioPageTable
{
  /**
   * @param  sfGuardUser $username
   * @return Doctrine_Query
   */
  public function addAuthorQuery(sfGuardUser $user, Doctrine_Query $q = null)
  {
    if ($q === null)
    {
      $q = $this->createQuery('p');
    }

    return $q->andWhere('p.author_id = ?', $user->id);
  }

  /**
   * Returns an array (tag => count) of the most popular tags and the
   * number of posts under that tag
   *
   * @param  integer$num The max number of tags to retrieve
   * @return array
   */
  public function getPopularTags($num)
  {
    return TagTable::getAllTagNameWithCount(null, array(
      'model' => 'ioBlog',
      'limit' => $num,
    ));
  }

  /**
   * Returns a collection of the sfGuardUser author objects
   *
   * @return Doctrine_Collection
   */
  public function getAuthors()
  {
    return Doctrine_Core::getTable('sfGuardUser')
      ->createQuery('u')
      ->select('u.*')
      ->innerJoin('u.Blogs b')
      ->orderBy('u.first_name ASC') // sort them alphabetically by first name
      ->execute();
  }
}