<?php

/**
 * PluginioBlog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginioBlog extends BaseioBlog
{
  public function getPreview()
  {
    if ($this['teaser'])
    {
      return $this['teaser'];
    }

    sfApplicationConfiguration::getActive()->loadHelpers('Text');

    return truncate_text(strip_tags($this['body']));
  }

  /**
   * Used as the string representation of the Author.
   *
   * Can be overridden to display something different for the author 
   *
   * @return string
   */
  public function getAuthorName()
  {
    return (string) $this->Author;
  }
}